name: Generate a new puzzle daily

on:
  schedule:
    - cron: "15 1 * * *"

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start
    - name: Move and commit puzzle file
      run: |
        mv complete.svg docs/grid.svg
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add docs/grid.svg
        timestamp=$(date -u)
        git commit -m "generated daily puzzle (${timestamp})" || exit 0
        git push
