name: Post to Mastodon

on:
  schedule:
    - cron: "0 0 * * 0"  # Executes the job at midnight UTC every Sunday

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Post to Mastodon
        uses: mastodon/share@v1
        with:
          instance-url: https://mastodon.scot
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          file: docs/grid.svg
