name: Post to Mastodon

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 0"  # Executes the job at midnight UTC every Sunday

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install mastodon-api

      - name: Run script
        run: node .github/scripts/post-to-mastodon.js ${{ secrets.MASTODON_ACCESS_TOKEN }} ${{ github.workspace }}/png/complete.png
