name: SVG to PNG Conversion

on:
  push:
    paths:
      - '**.svg'

permissions:
  contents: write

jobs:
  convert-svg-to-png:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cairosvg pillow

      - name: Convert SVG to PNG
        run: |
          mkdir -p png
          for file in *.svg; do
            filename="${file%.*}"
            cairosvg "$file" -o "png/${filename}.png"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add png
          git commit -m 'Convert SVG to PNG'
          git push
